[package]
name = "krisfy_balance"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib", "lib"]

[features]
no-entrypoint = []

[dependencies]
solana-program = "2.2.21"
anchor-lang = "0.30.1"
anchor-spl = { version = "0.30.1", features = ["token", "associated-token"] }
